"""add slack_integrations table

Revision ID: 0248ea7e10f5
Revises: ab5c2f8c6724
Create Date: 2025-11-20 15:34:23.966675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0248ea7e10f5'
down_revision = 'ab5c2f8c6724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('workspace_name', sa.String(), nullable=False),
    sa.Column('workspace_icon', sa.String(), nullable=True),
    sa.Column('bot_user_id', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_integrations_bot_id'), 'slack_integrations', ['bot_id'], unique=False)
    op.create_index(op.f('ix_slack_integrations_id'), 'slack_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_slack_integrations_user_id'), 'slack_integrations', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_key_usage_api_key_id'), 'api_key_usage', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_key_usage_timestamp_hour'), 'api_key_usage', ['timestamp_hour'], unique=False)
    op.alter_column('bot_api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bot_api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('bot_api_keys_key_hash_key', 'bot_api_keys', type_='unique')
    op.create_index(op.f('ix_bot_api_keys_bot_id'), 'bot_api_keys', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_api_keys_key_hash'), 'bot_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_bot_api_keys_user_id'), 'bot_api_keys', ['user_id'], unique=False)
    op.drop_index('idx_workflow_version_alias', table_name='bot_workflow_versions', postgresql_where='(api_endpoint_alias IS NOT NULL)')
    op.create_index(op.f('ix_bot_workflow_versions_api_endpoint_alias'), 'bot_workflow_versions', ['api_endpoint_alias'], unique=True)
    op.drop_index('idx_execution_api_key', table_name='workflow_execution_runs')
    op.drop_index('idx_execution_api_request_id', table_name='workflow_execution_runs')
    op.create_index(op.f('ix_workflow_execution_runs_api_key_id'), 'workflow_execution_runs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_runs_api_request_id'), 'workflow_execution_runs', ['api_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_execution_runs_api_request_id'), table_name='workflow_execution_runs')
    op.drop_index(op.f('ix_workflow_execution_runs_api_key_id'), table_name='workflow_execution_runs')
    op.create_index('idx_execution_api_request_id', 'workflow_execution_runs', ['api_request_id'], unique=False)
    op.create_index('idx_execution_api_key', 'workflow_execution_runs', ['api_key_id'], unique=False)
    op.drop_index(op.f('ix_bot_workflow_versions_api_endpoint_alias'), table_name='bot_workflow_versions')
    op.create_index('idx_workflow_version_alias', 'bot_workflow_versions', ['api_endpoint_alias'], unique=True, postgresql_where='(api_endpoint_alias IS NOT NULL)')
    op.drop_index(op.f('ix_bot_api_keys_user_id'), table_name='bot_api_keys')
    op.drop_index(op.f('ix_bot_api_keys_key_hash'), table_name='bot_api_keys')
    op.drop_index(op.f('ix_bot_api_keys_bot_id'), table_name='bot_api_keys')
    op.create_unique_constraint('bot_api_keys_key_hash_key', 'bot_api_keys', ['key_hash'])
    op.alter_column('bot_api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bot_api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_api_key_usage_timestamp_hour'), table_name='api_key_usage')
    op.drop_index(op.f('ix_api_key_usage_api_key_id'), table_name='api_key_usage')
    op.drop_index(op.f('ix_slack_integrations_user_id'), table_name='slack_integrations')
    op.drop_index(op.f('ix_slack_integrations_id'), table_name='slack_integrations')
    op.drop_index(op.f('ix_slack_integrations_bot_id'), table_name='slack_integrations')
    op.drop_table('slack_integrations')
    # ### end Alembic commands ###
