"""add marketplace tables

Revision ID: 71cd2ed7f42f
Revises: 9b8d02a748ec
Create Date: 2025-11-19 04:39:51.252251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71cd2ed7f42f'
down_revision = '9b8d02a748ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('publisher_team_id', sa.String(length=36), nullable=True),
    sa.Column('publisher_user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('screenshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['publisher_user_id'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['bot_workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    op.create_index('ix_marketplace_items_category_active', 'marketplace_items', ['category', 'is_active'], unique=False)
    op.create_index('ix_marketplace_items_download_count_desc', 'marketplace_items', [sa.text('download_count DESC')], unique=False)
    op.create_index(op.f('ix_marketplace_items_is_active'), 'marketplace_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketplace_items_published_at'), 'marketplace_items', ['published_at'], unique=False)
    op.create_index('ix_marketplace_items_published_at_desc', 'marketplace_items', [sa.text('published_at DESC')], unique=False)
    op.create_index(op.f('ix_marketplace_items_publisher_team_id'), 'marketplace_items', ['publisher_team_id'], unique=False)
    op.create_index('ix_marketplace_items_rating_desc', 'marketplace_items', [sa.text('rating_average DESC')], unique=False)
    op.create_index(op.f('ix_marketplace_items_workflow_version_id'), 'marketplace_items', ['workflow_version_id'], unique=True)
    op.create_table('marketplace_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_item_id'], ['marketplace_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_reviews_created_at'), 'marketplace_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketplace_reviews_marketplace_item_id'), 'marketplace_reviews', ['marketplace_item_id'], unique=False)
    op.create_index(op.f('ix_marketplace_reviews_user_id'), 'marketplace_reviews', ['user_id'], unique=False)
    op.create_index('uq_marketplace_reviews_item_user', 'marketplace_reviews', ['marketplace_item_id', 'user_id'], unique=True)
    op.alter_column('bot_workflow_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_bot_workflow_versions_bot_status', 'bot_workflow_versions', ['bot_id', 'status'], unique=False)
    op.create_index('ix_bot_workflow_versions_bot_version', 'bot_workflow_versions', ['bot_id', 'version'], unique=False)
    op.alter_column('bots', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('conversation_variables', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_variables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_conversation_variables_bot', table_name='conversation_variables')
    op.drop_index('ix_conversation_variables_conversation', table_name='conversation_variables')
    op.create_index(op.f('ix_conversation_variables_bot_id'), 'conversation_variables', ['bot_id'], unique=False)
    op.create_index(op.f('ix_conversation_variables_conversation_id'), 'conversation_variables', ['conversation_id'], unique=False)
    op.drop_constraint('knowledge_user_id_fkey', 'knowledge', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge', type_='foreignkey')
    op.create_foreign_key('knowledge_user_id_fkey', 'knowledge', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversation_variables_conversation_id'), table_name='conversation_variables')
    op.drop_index(op.f('ix_conversation_variables_bot_id'), table_name='conversation_variables')
    op.create_index('ix_conversation_variables_conversation', 'conversation_variables', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_variables_bot', 'conversation_variables', ['bot_id'], unique=False)
    op.alter_column('conversation_variables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_variables', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bots', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_bot_workflow_versions_bot_version', table_name='bot_workflow_versions')
    op.drop_index('ix_bot_workflow_versions_bot_status', table_name='bot_workflow_versions')
    op.alter_column('bot_workflow_versions', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index('uq_marketplace_reviews_item_user', table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_user_id'), table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_marketplace_item_id'), table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_created_at'), table_name='marketplace_reviews')
    op.drop_table('marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_items_workflow_version_id'), table_name='marketplace_items')
    op.drop_index('ix_marketplace_items_rating_desc', table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_publisher_team_id'), table_name='marketplace_items')
    op.drop_index('ix_marketplace_items_published_at_desc', table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_published_at'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_is_active'), table_name='marketplace_items')
    op.drop_index('ix_marketplace_items_download_count_desc', table_name='marketplace_items')
    op.drop_index('ix_marketplace_items_category_active', table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    # ### end Alembic commands ###
