"""Add widget deployment tables

Revision ID: 9b654bea4bf6
Revises: 544cb2fb2eed
Create Date: 2025-11-07 12:30:22.629694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b654bea4bf6'
down_revision = '544cb2fb2eed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_deployments',
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('widget_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allowed_domains', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('widget_config', sa.JSON(), nullable=False),
    sa.Column('embed_script', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_index('idx_deployment_bot_status', 'bot_deployments', ['bot_id', 'status'], unique=False)
    op.create_index('idx_deployment_widget_key', 'bot_deployments', ['widget_key'], unique=False)
    op.create_index(op.f('ix_bot_deployments_widget_key'), 'bot_deployments', ['widget_key'], unique=True)
    op.create_table('widget_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('session_token_hash', sa.String(length=256), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=256), nullable=True),
    sa.Column('user_info', sa.JSON(), nullable=True),
    sa.Column('fingerprint', sa.JSON(), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['bot_deployments.deployment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_session_deployment', 'widget_sessions', ['deployment_id'], unique=False)
    op.create_index('idx_session_fingerprint', 'widget_sessions', ['fingerprint_hash'], unique=False)
    op.create_index('idx_session_token_hash', 'widget_sessions', ['session_token_hash'], unique=False)
    op.create_index(op.f('ix_widget_sessions_fingerprint_hash'), 'widget_sessions', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_widget_sessions_refresh_token_hash'), 'widget_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_widget_sessions_session_token_hash'), 'widget_sessions', ['session_token_hash'], unique=True)
    op.create_table('widget_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['widget_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_event_created', 'widget_events', ['created_at'], unique=False)
    op.create_index('idx_event_session', 'widget_events', ['session_id'], unique=False)
    op.create_index('idx_event_type', 'widget_events', ['event_type'], unique=False)
    op.create_table('widget_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['widget_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_message_created', 'widget_messages', ['created_at'], unique=False)
    op.create_index('idx_message_session', 'widget_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_session', table_name='widget_messages')
    op.drop_index('idx_message_created', table_name='widget_messages')
    op.drop_table('widget_messages')
    op.drop_index('idx_event_type', table_name='widget_events')
    op.drop_index('idx_event_session', table_name='widget_events')
    op.drop_index('idx_event_created', table_name='widget_events')
    op.drop_table('widget_events')
    op.drop_index(op.f('ix_widget_sessions_session_token_hash'), table_name='widget_sessions')
    op.drop_index(op.f('ix_widget_sessions_refresh_token_hash'), table_name='widget_sessions')
    op.drop_index(op.f('ix_widget_sessions_fingerprint_hash'), table_name='widget_sessions')
    op.drop_index('idx_session_token_hash', table_name='widget_sessions')
    op.drop_index('idx_session_fingerprint', table_name='widget_sessions')
    op.drop_index('idx_session_deployment', table_name='widget_sessions')
    op.drop_table('widget_sessions')
    op.drop_index(op.f('ix_bot_deployments_widget_key'), table_name='bot_deployments')
    op.drop_index('idx_deployment_widget_key', table_name='bot_deployments')
    op.drop_index('idx_deployment_bot_status', table_name='bot_deployments')
    op.drop_table('bot_deployments')
    # ### end Alembic commands ###
