"""sync models with database schema

Revision ID: a38d586105bf
Revises: k0l1m2n3o4p5
Create Date: 2025-11-14 18:00:51.316081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a38d586105bf'
down_revision = 'k0l1m2n3o4p5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.alter_column('bot_workflow_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bot_workflow_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bot_workflow_versions', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_bot_workflow_versions_bot_id', table_name='bot_workflow_versions')
    op.drop_index('idx_bot_workflow_versions_status', table_name='bot_workflow_versions')
    op.drop_constraint('uq_bot_workflow_version', 'bot_workflow_versions', type_='unique')
    op.create_index(op.f('ix_bot_workflow_versions_bot_id'), 'bot_workflow_versions', ['bot_id'], unique=False)
    op.alter_column('bots', 'legacy_workflow',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('document_embeddings', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               comment='documents 테이블의 document_id',
               existing_nullable=True)
    # 벡터 인덱스는 성능상 중요하므로 유지
    # op.drop_index('document_embeddings_embedding_idx', table_name='document_embeddings', postgresql_using='hnsw')
    op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'embedded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='임베딩 완료 시간 (Workflow에서 실행)',
               existing_nullable=True)
    op.create_index(op.f('ix_model_pricing_id'), 'model_pricing', ['id'], unique=False)
    op.alter_column('workflow_execution_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_execution_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_workflow_runs_bot_id', table_name='workflow_execution_runs')
    op.drop_index('idx_workflow_runs_created_at', table_name='workflow_execution_runs')
    op.drop_index('idx_workflow_runs_session', table_name='workflow_execution_runs')
    op.create_index(op.f('ix_workflow_execution_runs_bot_id'), 'workflow_execution_runs', ['bot_id'], unique=False)
    op.create_index(op.f('ix_workflow_execution_runs_created_at'), 'workflow_execution_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_execution_runs_session_id'), 'workflow_execution_runs', ['session_id'], unique=False)
    op.alter_column('workflow_node_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_node_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_node_exec_run_id', table_name='workflow_node_executions')
    op.create_index(op.f('ix_workflow_node_executions_workflow_run_id'), 'workflow_node_executions', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_node_executions_workflow_run_id'), table_name='workflow_node_executions')
    op.create_index('idx_node_exec_run_id', 'workflow_node_executions', ['workflow_run_id'], unique=False)
    op.alter_column('workflow_node_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_node_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_workflow_execution_runs_session_id'), table_name='workflow_execution_runs')
    op.drop_index(op.f('ix_workflow_execution_runs_created_at'), table_name='workflow_execution_runs')
    op.drop_index(op.f('ix_workflow_execution_runs_bot_id'), table_name='workflow_execution_runs')
    op.create_index('idx_workflow_runs_session', 'workflow_execution_runs', ['session_id'], unique=False)
    op.create_index('idx_workflow_runs_created_at', 'workflow_execution_runs', ['created_at'], unique=False)
    op.create_index('idx_workflow_runs_bot_id', 'workflow_execution_runs', ['bot_id'], unique=False)
    op.alter_column('workflow_execution_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_execution_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_model_pricing_id'), table_name='model_pricing')
    op.alter_column('documents', 'embedded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='임베딩 완료 시간 (Workflow에서 실행)',
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    # 벡터 인덱스는 이미 존재하므로 재생성하지 않음
    # op.create_index('document_embeddings_embedding_idx', 'document_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.alter_column('document_embeddings', 'document_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='documents 테이블의 document_id',
               existing_nullable=True)
    op.alter_column('bots', 'legacy_workflow',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_bot_workflow_versions_bot_id'), table_name='bot_workflow_versions')
    op.create_unique_constraint('uq_bot_workflow_version', 'bot_workflow_versions', ['bot_id', 'version'])
    op.create_index('idx_bot_workflow_versions_status', 'bot_workflow_versions', ['bot_id', 'status'], unique=False)
    op.create_index('idx_bot_workflow_versions_bot_id', 'bot_workflow_versions', ['bot_id'], unique=False)
    op.alter_column('bot_workflow_versions', 'published_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_workflow_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bot_workflow_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###
