"""Add server_default to bot updated_at

Revision ID: d5adbd4a6a0c
Revises: 87e900e595e3
Create Date: 2025-11-21 23:45:34.435736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5adbd4a6a0c'
down_revision = '87e900e595e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bots_tags_gin', table_name='bots', postgresql_using='gin')
    # ### end Alembic commands ###

    # updated_at 컬럼에 server_default 추가
    op.alter_column('bots', 'updated_at',
                    server_default=sa.func.now(),
                    existing_type=sa.DateTime(timezone=True),
                    existing_nullable=True)

    # 기존 NULL 값들을 created_at 값으로 업데이트
    op.execute("""
        UPDATE bots
        SET updated_at = created_at
        WHERE updated_at IS NULL
    """)


def downgrade() -> None:
    # updated_at 컬럼의 server_default 제거
    op.alter_column('bots', 'updated_at',
                    server_default=None,
                    existing_type=sa.DateTime(timezone=True),
                    existing_nullable=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bots_tags_gin', 'bots', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
